import { LevelConfig } from './types';

export const TOTAL_LEVELS = 200;

export const LEVEL_CONFIGS: LevelConfig[] = [
    // Basic Phonics (Levels 1-30)
  { type: 'phonics', word: 'cat', letters: ['C', 'A', 'T'], description: 'Spell "CAT" for the magical cat! 🐱' },
  { type: 'phonics', word: 'bat', letters: ['B', 'A', 'T'], description: 'Spell "BAT" for the magical bat! 🦇' },
  { type: 'phonics', word: 'hat', letters: ['H', 'A', 'T'], description: 'Spell "HAT" for the wizard! 🧙' },
  { type: 'phonics', word: 'mat', letters: ['M', 'A', 'T'], description: 'Spell "MAT" for the magical rug! 🧹' },
  { type: 'phonics', word: 'rat', letters: ['R', 'A', 'T'], description: 'Spell "RAT" for the sneaky rat! 🐀' },
  { type: 'phonics', word: 'dog', letters: ['D', 'O', 'G'], description: 'Spell "DOG" for the loyal dog! 🐕' },
  { type: 'phonics', word: 'log', letters: ['L', 'O', 'G'], description: 'Spell "LOG" for the wooden log! 🌳' },
  { type: 'phonics', word: 'fog', letters: ['F', 'O', 'G'], description: 'Spell "FOG" in the misty forest! 🌫️' },
  { type: 'phonics', word: 'pig', letters: ['P', 'I', 'G'], description: 'Spell "PIG" for the pink pig! 🐽' },
  { type: 'phonics', word: 'big', letters: ['B', 'I', 'G'], description: 'Spell "BIG" for the giant! 👹' },
  { type: 'phonics', word: 'bug', letters: ['B', 'U', 'G'], description: 'Spell "BUG" for the little insect! 🐛' },
  { type: 'phonics', word: 'hug', letters: ['H', 'U', 'G'], description: 'Spell "HUG" to show love! 🤗' },
  { type: 'phonics', word: 'sun', letters: ['S', 'U', 'N'], description: 'Spell "SUN" for bright day! ☀️' },
  { type: 'phonics', word: 'fun', letters: ['F', 'U', 'N'], description: 'Spell "FUN" at the party! 🎉' },
  // Advanced Phonics (Levels 15-50)
  { type: 'phonics', word: 'stop', letters: ['S', 'T', 'O', 'P'], description: 'Spell "STOP" at the sign! 🛑' },
  { type: 'phonics', word: 'clap', letters: ['C', 'L', 'A', 'P'], description: 'Spell "CLAP" to applaud! 👏' },
  { type: 'phonics', word: 'flag', letters: ['F', 'L', 'A', 'G'], description: 'Spell "FLAG" for the country! 🇺🇸' },
  { type: 'phonics', word: 'drum', letters: ['D', 'R', 'U', 'M'], description: 'Spell "DRUM" to beat loud! 🥁' },
  { type: 'phonics', word: 'ship', letters: ['S', 'H', 'I', 'P'], description: 'Spell "SHIP" on the sea! 🚢' },
  { type: 'phonics', word: 'chip', letters: ['C', 'H', 'I', 'P'], description: 'Spell "CHIP" for snack time! 🥔' },
  { type: 'phonics', word: 'thin', letters: ['T', 'H', 'I', 'N'], description: 'Spell "THIN" like a needle! 🪡' },
  { type: 'phonics', word: 'cake', letters: ['C', 'A', 'K', 'E'], description: 'Spell "CAKE" for birthday! 🎂' },
  { type: 'phonics', word: 'bike', letters: ['B', 'I', 'K', 'E'], description: 'Spell "BIKE" to ride fast! 🚲' },
  { type: 'phonics', word: 'rain', letters: ['R', 'A', 'I', 'N'], description: 'Spell "RAIN" from clouds! 🌧️' },
  { type: 'phonics', word: 'train', letters: ['T', 'R', 'A', 'I', 'N'], description: 'Spell "TRAIN" chug chug! 🚂' },
  { type: 'phonics', word: 'feet', letters: ['F', 'E', 'E', 'T'], description: 'Spell "FEET" to walk! 👣' },
  { type: 'phonics', word: 'meet', letters: ['M', 'E', 'E', 'T'], description: 'Spell "MEET" your friends! 👋' },
  { type: 'phonics', word: 'tree', letters: ['T', 'R', 'E', 'E'], description: 'Spell "TREE" tall and green! 🌲' },
  { type: 'phonics', word: 'clean', letters: ['C', 'L', 'E', 'A', 'N'], description: 'Spell "CLEAN" the room! 🧹' },
  { type: 'phonics', word: 'dream', letters: ['D', 'R', 'E', 'A', 'M'], description: 'Spell "DREAM" at night! 💭' },
  { type: 'phonics', word: 'boat', letters: ['B', 'O', 'A', 'T'], description: 'Spell "BOAT" to sail! 🚤' },
  { type: 'phonics', word: 'goat', letters: ['G', 'O', 'A', 'T'], description: 'Spell "GOAT" the climber! 🐐' },
  { type: 'phonics', word: 'play', letters: ['P', 'L', 'A', 'Y'], description: 'Spell "PLAY" all day! 🛝' },
  { type: 'phonics', word: 'jump', letters: ['J', 'U', 'M', 'P'], description: 'Spell "JUMP" high! 🦘' },
  { type: 'phonics', word: 'swim', letters: ['S', 'W', 'I', 'M'], description: 'Spell "SWIM" in pool! 🏊' },
  { type: 'phonics', word: 'queen', letters: ['Q', 'U', 'E', 'E', 'N'], description: 'Spell "QUEEN" royal! 👑' },
  // Non-Phonics Levels (Now starting from 38)
  { type: 'shape', shape: '🌙', description: 'Match the enchanted 🌙!' },
  { type: 'shape', shape: '🔴', description: 'Match the glowing 🔴!' },
  { type: 'shape', shape: '⭐', description: 'Match the sparkly ⭐!' },
  { type: 'shape', shape: '❤️', description: 'Match the enchanted ❤️!' },
  { type: 'shape', shape: '💎', description: 'Match the sparkly 💎!' },
  { type: 'number', num: 4, stars: '⭐⭐⭐⭐', description: 'Count the stars: How many magical stars?' },
  { type: 'number', num: 7, stars: '⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many shining stars?' },
  { type: 'number', num: 3, stars: '⭐⭐⭐', description: 'Count the stars: How many twinkling stars?' },
  { type: 'number', num: 9, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many magical stars?' },
  { type: 'number', num: 5, stars: '⭐⭐⭐⭐⭐', description: 'Count the stars: How many shining stars?' },
  { type: 'color', emoji: '🟡', name: 'yellow', description: 'Match the color: Click the yellow potion!' },
  { type: 'color', emoji: '🟢', name: 'green', description: 'Match the color: Click the green wand!' },
  { type: 'color', emoji: '🔴', name: 'red', description: 'Match the color: Click the red gem!' },
  { type: 'color', emoji: '🟣', name: 'purple', description: 'Match the color: Click the purple potion!' },
  { type: 'color', emoji: '🔵', name: 'blue', description: 'Match the color: Click the blue gem!' },
  { type: 'sort', items: ['2', '3', '7'], description: 'Sort the numbers in order: Drag to arrange 2, 3, 7' },
  { type: 'sort', items: ['3', '5', '7'], description: 'Sort the numbers in order: Drag to arrange 3, 5, 7' },
  { type: 'sort', items: ['1', '6', '10'], description: 'Sort the numbers in order: Drag to arrange 1, 6, 10' },
  { type: 'sort', items: ['4', '8', '9'], description: 'Sort the numbers in order: Drag to arrange 4, 8, 9' },
  { type: 'sort', items: ['5', '6', '7'], description: 'Sort the numbers in order: Drag to arrange 5, 6, 7' },
  { type: 'phonics', word: 'pat', letters: ['P', 'A', 'T'], description: 'Spell "PAT" to pat the dog! 🐕' },
  { type: 'phonics', word: 'hog', letters: ['H', 'O', 'G'], description: 'Spell "HOG" for the farm hog! 🐷' },
  { type: 'phonics', word: 'dig', letters: ['D', 'I', 'G'], description: 'Spell "DIG" to find treasure! ⛏️' },
  { type: 'phonics', word: 'wig', letters: ['W', 'I', 'G'], description: 'Spell "WIG" for the funny hair! 💇' },
  { type: 'phonics', word: 'mug', letters: ['M', 'U', 'G'], description: 'Spell "MUG" for hot cocoa! ☕' },
  { type: 'phonics', word: 'rug', letters: ['R', 'U', 'G'], description: 'Spell "RUG" for the cozy rug! 🏠' },
  { type: 'phonics', word: 'trap', letters: ['T', 'R', 'A', 'P'], description: 'Spell "TRAP" for the mouse! 🐭' },
  { type: 'phonics', word: 'whip', letters: ['W', 'H', 'I', 'P'], description: 'Spell "WHIP" the cream! 🥛' },
  { type: 'phonics', word: 'like', letters: ['L', 'I', 'K', 'E'], description: 'Spell "LIKE" your favorite! ❤️' },
  { type: 'phonics', word: 'mail', letters: ['M', 'A', 'I', 'L'], description: 'Spell "MAIL" in the box! 📬' },
  { type: 'phonics', word: 'sail', letters: ['S', 'A', 'I', 'L'], description: 'Spell "SAIL" on the boat! ⛵' },
  { type: 'phonics', word: 'team', letters: ['T', 'E', 'A', 'M'], description: 'Spell "TEAM" to win! 🏆' },
  { type: 'phonics', word: 'bread', letters: ['B', 'R', 'E', 'A', 'D'], description: 'Spell "BREAD" for toast! 🍞' },
  { type: 'phonics', word: 'coast', letters: ['C', 'O', 'A', 'S', 'T'], description: 'Spell "COAST" by the sea! 🏖️' },
  { type: 'phonics', word: 'stay', letters: ['S', 'T', 'A', 'Y'], description: 'Spell "STAY" here! 🏠' },
  { type: 'phonics', word: 'bump', letters: ['B', 'U', 'M', 'P'], description: 'Spell "BUMP" ouch! 😵' },
  { type: 'phonics', word: 'twig', letters: ['T', 'W', 'I', 'G'], description: 'Spell "TWIG" from tree! 🌿' },
  { type: 'phonics', word: 'quick', letters: ['Q', 'U', 'I', 'C', 'K'], description: 'Spell "QUICK" like fox! 🦊' },
  { type: 'shape', shape: '🔲', description: 'Match the sparkly 🔲!' },
  { type: 'shape', shape: '🔵', description: 'Match the enchanted 🔵!' },
  { type: 'shape', shape: '🟡', description: 'Match the glowing 🟡!' },
  { type: 'number', num: 18, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many shining stars?' },
  { type: 'number', num: 13, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many twinkling stars?' },
  { type: 'number', num: 11, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many magical stars?' },
  { type: 'color', emoji: '🩷', name: 'pink', description: 'Match the color: Click the pink gem!' },
  { type: 'color', emoji: '🟠', name: 'orange', description: 'Match the color: Click the orange wand!' },
  { type: 'color', emoji: '⚪', name: 'white', description: 'Match the color: Click the white potion!' },
  { type: 'sort', items: ['2', '3', '4'], description: 'Sort the numbers in order: Drag to arrange 2, 3, 4' },
  { type: 'sort', items: ['6', '7', '8'], description: 'Sort the numbers in order: Drag to arrange 6, 7, 8' },
  { type: 'sort', items: ['5', '8', '9'], description: 'Sort the numbers in order: Drag to arrange 5, 8, 9' },
  { type: 'phonics', word: 'sat', letters: ['S', 'A', 'T'], description: 'Spell "SAT" on the magical chair! 🪑' },
  { type: 'phonics', word: 'jog', letters: ['J', 'O', 'G'], description: 'Spell "JOG" to run fast! 🏃' },
  { type: 'phonics', word: 'fig', letters: ['F', 'I', 'G'], description: 'Spell "FIG" for the fruit! 🍇' },
  { type: 'phonics', word: 'jug', letters: ['J', 'U', 'G'], description: 'Spell "JUG" for the water jug! 🏺' },
  { type: 'phonics', word: 'free', letters: ['F', 'R', 'E', 'E'], description: 'Spell "FREE" like a bird! 🐦' },
  { type: 'phonics', word: 'three', letters: ['T', 'H', 'R', 'E', 'E'], description: 'Spell "THREE" count them! 3️⃣' },
  { type: 'phonics', word: 'float', letters: ['F', 'L', 'O', 'A', 'T'], description: 'Spell "FLOAT" on water! 🛶' },
  { type: 'phonics', word: 'spray', letters: ['S', 'P', 'R', 'A', 'Y'], description: 'Spell "SPRAY" the flowers! 🌸' },
  { type: 'phonics', word: 'twist', letters: ['T', 'W', 'I', 'S', 'T'], description: 'Spell "TWIST" around! 🌀' },
  { type: 'shape', shape: '🔺', description: 'Match the pointy 🔺!' },
  { type: 'number', num: 2, stars: '⭐⭐', description: 'Count the stars: How many twinkling stars?' },
  { type: 'number', num: 17, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many twinkling stars?' },
  { type: 'number', num: 20, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count the stars: How many magical stars?' },
  { type: 'color', emoji: '⚫', name: 'black', description: 'Match the color: Click the black potion!' },
  { type: 'sort', items: ['3', '6', '7'], description: 'Sort the numbers in order: Drag to arrange 3, 6, 7' },
  { type: 'sort', items: ['6', '8', '10'], description: 'Sort the numbers in order: Drag to arrange 6, 8, 10' },
  { type: 'phonics', word: 'fat', letters: ['F', 'A', 'T'], description: 'Spell "FAT" for the plump pig! 🐖' },
  { type: 'phonics', word: 'cog', letters: ['C', 'O', 'G'], description: 'Spell "COG" for the gear! ⚙️' },
  { type: 'phonics', word: 'gig', letters: ['G', 'I', 'G'], description: 'Spell "GIG" for the music show! 🎸' },
  { type: 'phonics', word: 'dug', letters: ['D', 'U', 'G'], description: 'Spell "DUG" the hole deep! 🕳️' },
  { type: 'phonics', word: 'tug', letters: ['T', 'U', 'G'], description: 'Spell "TUG" the rope strong! 🪢' },
  { type: 'phonics', word: 'sheet', letters: ['S', 'H', 'E', 'E', 'T'], description: 'Spell "SHEET" on the bed! 🛏️' },
  { type: 'phonics', word: 'steam', letters: ['S', 'T', 'E', 'A', 'M'], description: 'Spell "STEAM" from kettle! ☕' },
  { type: 'phonics', word: 'thread', letters: ['T', 'H', 'R', 'E', 'A', 'D'], description: 'Spell "THREAD" for sewing! 🪡' },
  { type: 'phonics', word: 'clay', letters: ['C', 'L', 'A', 'Y'], description: 'Spell "CLAY" to mold! 🏺' },
  { type: 'phonics', word: 'lump', letters: ['L', 'U', 'M', 'P'], description: 'Spell "LUMP" of sugar! 🍬' },
  { type: 'phonics', word: 'pump', letters: ['P', 'U', 'M', 'P'], description: 'Spell "PUMP" the water! 💧' },
  { type: 'phonics', word: 'pail', letters: ['P', 'A', 'I', 'L'], description: 'Spell "PAIL" for water! 🪣' },
  { type: 'phonics', word: 'shop', letters: ['S', 'H', 'O', 'P'], description: 'Spell "SHOP" at the magic store! 🛍️' },
  { type: 'phonics', word: 'chin', letters: ['C', 'H', 'I', 'N'], description: 'Spell "CHIN" on the friendly giant! 😊' },
  { type: 'phonics', word: 'rich', letters: ['R', 'I', 'C', 'H'], description: 'Spell "RICH" to find the treasure chest! 💰' },
  { type: 'phonics', word: 'path', letters: ['P', 'A', 'T', 'H'], description: 'Spell "PATH" to follow the enchanted trail! 🛤️' },
  { type: 'phonics', word: 'fish', letters: ['F', 'I', 'S', 'H'], description: 'Spell "FISH" for the swimming fish! 🐠' },
  { type: 'phonics', word: 'brush', letters: ['B', 'R', 'U', 'S', 'H'], description: 'Spell "BRUSH" the unicorn\'s hair! 🦄' },
  { type: 'phonics', word: 'feed', letters: ['F', 'E', 'E', 'D'], description: 'Spell "FEED" the hungry dragon! 🐲' },
  { type: 'phonics', word: 'seed', letters: ['S', 'E', 'E', 'D'], description: 'Spell "SEED" to grow a magic beanstalk! 🌱' },
  { type: 'phonics', word: 'read', letters: ['R', 'E', 'A', 'D'], description: 'Spell "READ" from the ancient scroll! 📜' },
  { type: 'phonics', word: 'leaf', letters: ['L', 'E', 'A', 'F'], description: 'Spell "LEAF" from the talking tree! 🍃' },
  { type: 'phonics', word: 'pain', letters: ['P', 'A', 'I', 'N'], description: 'Spell "PAIN" to make the ouchie go away! 🩹' },
  { type: 'phonics', word: 'wait', letters: ['W', 'A', 'I', 'T'], description: 'Spell "WAIT" for the potion to bubble! 🧪' },
  { type: 'phonics', word: 'road', letters: ['R', 'O', 'A', 'D'], description: 'Spell "ROAD" on the yellow brick road! 🟡' },
  { type: 'phonics', word: 'toad', letters: ['T', 'O', 'A', 'D'], description: 'Spell "TOAD" for the croaking friend! 🐸' },
  { type: 'phonics', word: 'blue', letters: ['B', 'L', 'U', 'E'], description: 'Spell "BLUE" like the deep ocean! 🌊' },
  { type: 'phonics', word: 'glue', letters: ['G', 'L', 'U', 'E'], description: 'Spell "GLUE" to fix the broken wand! ✨' },
  { type: 'phonics', word: 'crab', letters: ['C', 'R', 'A', 'B'], description: 'Spell "CRAB" on the sandy beach! 🦀' },
  { type: 'phonics', word: 'grin', letters: ['G', 'R', 'I', 'N'], description: 'Spell "GRIN" with the Cheshire cat! 😄' },
  { type: 'phonics', word: 'frog', letters: ['F', 'R', 'O', 'G'], description: 'Spell "FROG" to help the prince! 👑' },
  { type: 'phonics', word: 'plum', letters: ['P', 'L', 'U', 'M'], description: 'Spell "PLUM" for a sweet magical fruit! 🍑' },
  { type: 'phonics', word: 'stem', letters: ['S', 'T', 'E', 'M'], description: 'Spell "STEM" of the enchanted rose! 🌹' },
  { type: 'phonics', word: 'spin', letters: ['S', 'P', 'I', 'N'], description: 'Spell "SPIN" like a whirlwind! 🌪️' },
  { type: 'phonics', word: 'star', letters: ['S', 'T', 'A', 'R'], description: 'Spell "STAR" for the shooting star! 🌠' },
  { type: 'phonics', word: 'moon', letters: ['M', 'O', 'O', 'N'], description: 'Spell "MOON" that shines so bright! 🌕' },
  { type: 'phonics', word: 'fork', letters: ['F', 'O', 'R', 'K'], description: 'Spell "FORK" for the royal feast! 🍴' },
  { type: 'phonics', word: 'corn', letters: ['C', 'O', 'R', 'N'], description: 'Spell "CORN" from the magical fields! 🌽' },
  { type: 'phonics', word: 'book', letters: ['B', 'O', 'O', 'K'], description: 'Spell "BOOK" of powerful spells! 📖' },
  { type: 'phonics', word: 'hook', letters: ['H', 'O', 'O', 'K'], description: 'Spell "HOOK" for the pirate captain! 🏴‍☠️' },
  { type: 'phonics', word: 'wind', letters: ['W', 'I', 'N', 'D'], description: 'Spell "WIND" that whispers secrets! 🌬️' },
  { type: 'phonics', word: 'farm', letters: ['F', 'A', 'R', 'M'], description: 'Spell "FARM" with magical animals! 🚜' },
  { type: 'number', num: 21, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 21 sparkling gems!' },
  { type: 'number', num: 22, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 22 friendly ghosts!' },
  { type: 'number', num: 23, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 23 buzzing bees!' },
  { type: 'number', num: 24, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 24 sleepy sloths!' },
  { type: 'number', num: 25, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 25 party poppers!' },
  { type: 'number', num: 14, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 14 magical keys!' },
  { type: 'number', num: 16, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 16 lucky clovers!' },
  { type: 'number', num: 15, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 15 colorful balloons!' },
  { type: 'number', num: 19, stars: '⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐', description: 'Count 19 sweet lollipops!' },
  { type: 'number', num: 6, stars: '⭐⭐⭐⭐⭐⭐', description: 'Count 6 cuddly teddy bears!' },
  { type: 'sort', items: ['2', '4', '6', '8'], description: 'Sort the even numbers: 2, 4, 6, 8' },
  { type: 'sort', items: ['1', '3', '5', '7'], description: 'Sort the odd numbers: 1, 3, 5, 7' },
  { type: 'sort', items: ['10', '20', '30'], description: 'Sort by tens: 10, 20, 30' },
  { type: 'sort', items: ['5', '10', '15'], description: 'Sort by fives: 5, 10, 15' },
  { type: 'sort', items: ['1', '2', '8', '9'], description: 'Sort these mixed up numbers!' },
  { type: 'sort', items: ['3', '4', '7', '9'], description: 'Put these numbers in the right order!' },
  { type: 'sort', items: ['11', '15', '19'], description: 'Sort these teen numbers!' },
  { type: 'sort', items: ['4', '6', '9', '12'], description: 'Arrange the numbers from small to big!' },
  { type: 'sort', items: ['1', '5', '9'], description: 'Sort the treasure map numbers!' },
  { type: 'sort', items: ['8', '9', '10', '11'], description: 'Put the sequence in order!' },
  { type: 'shape', shape: '💠', description: 'Match the diamond shard! 💠' },
  { type: 'shape', shape: '🌀', description: 'Match the magical swirl! 🌀' },
  { type: 'shape', shape: '🛑', description: 'Match the stop sign shape! 🛑' },
  { type: 'shape', shape: '✅', description: 'Match the check mark! ✅' },
  { type: 'shape', shape: '❌', description: 'Match the crossing mark! ❌' },
  { type: 'color', emoji: '🟤', name: 'brown', description: 'Match the color: Click the brown teddy bear! 🧸' },
  { type: 'color', emoji: '⚫', name: 'black', description: 'Match the color: Click the black cat\'s hat! 🐈‍⬛' },
  { type: 'color', emoji: '⚪', name: 'white', description: 'Match the color: Click the fluffy white cloud! ☁️' },
  { type: 'color', emoji: '🟠', name: 'orange', description: 'Match the color: Click the juicy orange fruit! 🍊' },
  { type: 'color', emoji: '🩷', name: 'pink', description: 'Match the color: Click the pink piggy bank! 🐷' },
  { type: 'phonics', word: 'nest', letters: ['N', 'E', 'S', 'T'], description: 'Spell "NEST" for the baby bird! 🐦' },
  { type: 'phonics', word: 'hand', letters: ['H', 'A', 'N', 'D'], description: 'Spell "HAND" to wave hello! 👋' },
  { type: 'phonics', word: 'sand', letters: ['S', 'A', 'N', 'D'], description: 'Spell "SAND" to build a sandcastle! 🏰' },
  { type: 'phonics', word: 'milk', letters: ['M', 'I', 'L', 'K'], description: 'Spell "MILK" for the thirsty kitten! 🥛' },
  { type: 'phonics', word: 'gift', letters: ['G', 'I', 'F', 'T'], description: 'Spell "GIFT" to open the present! 🎁' },
  { type: 'phonics', word: 'desk', letters: ['D', 'E', 'S', 'K'], description: 'Spell "DESK" for the wizard\'s studies! 🖋️' },
  { type: 'phonics', word: 'help', letters: ['H', 'E', 'L', 'P'], description: 'Spell "HELP" the lost fairy! 🧚‍♀️' },
  { type: 'phonics', word: 'gold', letters: ['G', 'O', 'L', 'D'], description: 'Spell "GOLD" from the dragon\'s hoard! 🪙' },
  { type: 'phonics', word: 'fast', letters: ['F', 'A', 'S', 'T'], description: 'Spell "FAST" like a lightning bolt! ⚡' },
  { type: 'phonics', word: 'soft', letters: ['S', 'O', 'F', 'T'], description: 'Spell "SOFT" like a fluffy sheep! 🐑' },
];
